"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.local_obit_documents_inner import LocalObitDocumentsInner
from obada_client.model.local_obit_metadata_inner import LocalObitMetadataInner
from obada_client.model.local_obit_structured_data_inner import LocalObitStructuredDataInner
globals()['LocalObitDocumentsInner'] = LocalObitDocumentsInner
globals()['LocalObitMetadataInner'] = LocalObitMetadataInner
globals()['LocalObitStructuredDataInner'] = LocalObitStructuredDataInner
from obada_client.model.local_obit import LocalObit


class TestLocalObit(unittest.TestCase):
    """LocalObit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalObit(self):
        """Test LocalObit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalObit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
