"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.obit_definition import ObitDefinition


class TestObitDefinition(unittest.TestCase):
    """ObitDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObitDefinition(self):
        """Test ObitDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObitDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
