"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import obada_client
from obada_client.api.nft_api import NFTApi  # noqa: E501


class TestNFTApi(unittest.TestCase):
    """NFTApi unit test stubs"""

    def setUp(self):
        self.api = NFTApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mint(self):
        """Test case for mint

        Mints NFT  # noqa: E501
        """
        pass

    def test_nft(self):
        """Test case for nft

        Fetch NFT from OBADA blockchain Node  # noqa: E501
        """
        pass

    def test_send(self):
        """Test case for send

        Send NFT to another address  # noqa: E501
        """
        pass

    def test_update_metadata(self):
        """Test case for update_metadata

        Update NFT metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
