"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.client_obit import ClientObit
globals()['ClientObit'] = ClientObit
from openapi_client.model.client_obit_response import ClientObitResponse


class TestClientObitResponse(unittest.TestCase):
    """ClientObitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientObitResponse(self):
        """Test ClientObitResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClientObitResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
