"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import obada_client
from obada_client.api.utils_api import UtilsApi  # noqa: E501


class TestUtilsApi(unittest.TestCase):
    """UtilsApi unit test stubs"""

    def setUp(self):
        self.api = UtilsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_checksum(self):
        """Test case for generate_checksum

        Generates Obit checksum  # noqa: E501
        """
        pass

    def test_generate_did(self):
        """Test case for generate_did

        Generate Obit DID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
