"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.obit_api import ObitApi  # noqa: E501


class TestObitApi(unittest.TestCase):
    """ObitApi unit test stubs"""

    def setUp(self):
        self.api = ObitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_obit_from_chain(self):
        """Test case for download_obit_from_chain

        Download Obit from Blockchain  # noqa: E501
        """
        pass

    def test_fetch_obit_from_chain(self):
        """Test case for fetch_obit_from_chain

        Get Obit From Blockchain  # noqa: E501
        """
        pass

    def test_generate_obit_def(self):
        """Test case for generate_obit_def

        Generate Obit Definition  # noqa: E501
        """
        pass

    def test_get_client_obit(self):
        """Test case for get_client_obit

        Get Client Obit  # noqa: E501
        """
        pass

    def test_save_client_obit(self):
        """Test case for save_client_obit

        Save Client Obit  # noqa: E501
        """
        pass

    def test_upload_obit(self):
        """Test case for upload_obit

        Upload Obit to Blockchain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
