"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.obit_history import ObitHistory
globals()['ObitHistory'] = ObitHistory
from obada_client.model.history200_response import History200Response


class TestHistory200Response(unittest.TestCase):
    """History200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistory200Response(self):
        """Test History200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = History200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
