"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.wallet_exists_error import WalletExistsError


class TestWalletExistsError(unittest.TestCase):
    """WalletExistsError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletExistsError(self):
        """Test WalletExistsError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WalletExistsError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
