"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import obada_client
from obada_client.api.accounts_api import AccountsApi  # noqa: E501


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account(self):
        """Test case for account

        Fetches an information about single account  # noqa: E501
        """
        pass

    def test_accounts(self):
        """Test case for accounts

        Returns a list of OBADA accounts  # noqa: E501
        """
        pass

    def test_balance(self):
        """Test case for balance

        Shows account balance of OBADA address  # noqa: E501
        """
        pass

    def test_export_account(self):
        """Test case for export_account

        Export OBADA account (private key) from client-helper  # noqa: E501
        """
        pass

    def test_get_mnemonic(self):
        """Test case for get_mnemonic

        Fetching an existing mnemonic phrase  # noqa: E501
        """
        pass

    def test_import_account(self):
        """Test case for import_account

        Imports an existing OBADA account (private key) to the client-helper user profile  # noqa: E501
        """
        pass

    def test_import_wallet(self):
        """Test case for import_wallet

        Imports an existing HD wallet to the client-helper user profile  # noqa: E501
        """
        pass

    def test_new_account(self):
        """Test case for new_account

        Creates a new OBADA account from HD wallet master key  # noqa: E501
        """
        pass

    def test_new_mnemonic(self):
        """Test case for new_mnemonic

        Generate a new mnemonic phrase for seeding wallet  # noqa: E501
        """
        pass

    def test_new_wallet(self):
        """Test case for new_wallet

        Creates profile HD wallet  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        Register a new client-helper user profile  # noqa: E501
        """
        pass

    def test_send_coins(self):
        """Test case for send_coins

        Send coins from selected account  # noqa: E501
        """
        pass

    def test_update_account(self):
        """Test case for update_account

        Sets account specific information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
