"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import obada_client
from obada_client.api.accounts_api import AccountsApi  # noqa: E501


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_balance(self):
        """Test case for balance

        Shows account balance of OBADA address  # noqa: E501
        """
        pass

    def test_create_account(self):
        """Test case for create_account

        Creates a new Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
