"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.unprocessable_entity_fields_inner import UnprocessableEntityFieldsInner


class TestUnprocessableEntityFieldsInner(unittest.TestCase):
    """UnprocessableEntityFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnprocessableEntityFieldsInner(self):
        """Test UnprocessableEntityFieldsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnprocessableEntityFieldsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
