"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.obit import Obit
from obada_client.model.obits_meta import ObitsMeta
globals()['Obit'] = Obit
globals()['ObitsMeta'] = ObitsMeta
from obada_client.model.obits import Obits


class TestObits(unittest.TestCase):
    """Obits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObits(self):
        """Test Obits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Obits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
