"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.local_obit_documents import LocalObitDocuments
from obada_client.model.local_obit_metadata import LocalObitMetadata
from obada_client.model.local_obit_structured_data import LocalObitStructuredData
globals()['LocalObitDocuments'] = LocalObitDocuments
globals()['LocalObitMetadata'] = LocalObitMetadata
globals()['LocalObitStructuredData'] = LocalObitStructuredData
from obada_client.model.client_obit import ClientObit


class TestClientObit(unittest.TestCase):
    """ClientObit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientObit(self):
        """Test ClientObit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClientObit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
