"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.obits_meta import ObitsMeta


class TestObitsMeta(unittest.TestCase):
    """ObitsMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObitsMeta(self):
        """Test ObitsMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObitsMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
