"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import obada_client
from obada_client.model.block_chain_obit import BlockChainObit
globals()['BlockChainObit'] = BlockChainObit
from obada_client.model.block_chain_obit_response import BlockChainObitResponse


class TestBlockChainObitResponse(unittest.TestCase):
    """BlockChainObitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockChainObitResponse(self):
        """Test BlockChainObitResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockChainObitResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
