"""
    OBADA Client Helper API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.local_obit_metadata import LocalObitMetadata


class TestLocalObitMetadata(unittest.TestCase):
    """LocalObitMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalObitMetadata(self):
        """Test LocalObitMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalObitMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
