# flake8: noqa

"""
    OBADA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: techops@obada.io
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from obada_client.api_client import ApiClient

# import Configuration
from obada_client.configuration import Configuration

# import exceptions
from obada_client.exceptions import OpenApiException
from obada_client.exceptions import ApiAttributeError
from obada_client.exceptions import ApiTypeError
from obada_client.exceptions import ApiValueError
from obada_client.exceptions import ApiKeyError
from obada_client.exceptions import ApiException
